language: node_js
node_js: stable
env:
  global:
   - COMMIT=${TRAVIS_COMMIT::6}

sudo: required
services:
- docker
script:
  - python tag.py
  - cd website
  - npm run build 
  - cd ..
after_success:
  docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t shubh214/litmus-openebs-docs:1.1.18 . && docker push shubh214/litmus-openebs-docs:1.1.18; 
